// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5NSiowXuWlhyNdPzf0jde8yGiroLUZ0',
    appId: '1:177501334482:web:da556de24bf93dc059b60b',
    messagingSenderId: '177501334482',
    projectId: 'ocr-2-65da2',
    authDomain: 'ocr-2-65da2.firebaseapp.com',
    storageBucket: 'ocr-2-65da2.firebasestorage.app',
    measurementId: 'G-P6TELQ1ELW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3KTMLSKWQ1VAjj7C55zshfqcGv1Jlc-M',
    appId: '1:177501334482:android:31cd5ee40c1be10a59b60b',
    messagingSenderId: '177501334482',
    projectId: 'ocr-2-65da2',
    storageBucket: 'ocr-2-65da2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEYSpFOVsBQG1V8gS5F7sGbvqA1TMHKp0',
    appId: '1:177501334482:ios:c45629ca024ff48b59b60b',
    messagingSenderId: '177501334482',
    projectId: 'ocr-2-65da2',
    storageBucket: 'ocr-2-65da2.firebasestorage.app',
    iosBundleId: 'com.example.ocr2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEYSpFOVsBQG1V8gS5F7sGbvqA1TMHKp0',
    appId: '1:177501334482:ios:c45629ca024ff48b59b60b',
    messagingSenderId: '177501334482',
    projectId: 'ocr-2-65da2',
    storageBucket: 'ocr-2-65da2.firebasestorage.app',
    iosBundleId: 'com.example.ocr2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp5NSiowXuWlhyNdPzf0jde8yGiroLUZ0',
    appId: '1:177501334482:web:3f8331fccf771bc359b60b',
    messagingSenderId: '177501334482',
    projectId: 'ocr-2-65da2',
    authDomain: 'ocr-2-65da2.firebaseapp.com',
    storageBucket: 'ocr-2-65da2.firebasestorage.app',
    measurementId: 'G-NN1KB9QFJ7',
  );

}